name: Cloud_Sentry Actions

on:
  push:
  workflow_dispatch:

jobs:
  cloud_scan:
    name: Cloud Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (optional)
        run: pip install -r requirements.txt || true

      - name: Run CloudSentry
        run: python cloudsentry.py
      
      - name: Run CloudSentry (real AWS)
        env:
            CLOUDSENTRY_MODE: aws
        run: python cloudsentry.py
